import 'package:furnitureui/model/product_model.dart';

class Constants {
  static List<ProductModel> chairs = [
    ProductModel(
      id: 1,
      imagePath: 'assets/1.png',
      price: 240,
      name: 'Matteo Armchair',
      productType: 'Chair',
      description: '',
    ),
    ProductModel(
      id: 2,
      imagePath: 'assets/2.png',
      price: 240,
      name: 'Araceli Armchair',
      productType: 'Chair',
      description: '',
    ),
    ProductModel(
      id: 3,
      imagePath: 'assets/3.png',
      price: 760,
      name: 'Primose Armchair',
      productType: 'Chair',
      description: '',
    ),
    ProductModel(
      id: 4,
      imagePath: 'assets/4.png',
      price: 332,
      name: 'Nolin Armchair',
      productType: 'Chair',
      description: '',
    ),
    ProductModel(
      id: 5,
      imagePath: 'assets/5.png',
      price: 500,
      name: 'Crandall Armchair',
      productType: 'Chair',
      description: '',
    ),
    ProductModel(
      id: 6,
      imagePath: 'assets/6.png',
      price: 550,
      name: 'Donham Armchair',
      productType: 'Chair',
      description: '',
    ),
  ];
  static List<ProductModel> sofa = [
    ProductModel(
      id: 1,
      imagePath: 'assets/sofa1.png',
      price: 240,
      name: 'Matteo sofa',
      productType: 'sofa',
      description: '',
    ),
    ProductModel(
      id: 2,
      imagePath: 'assets/sofa2.png',
      price: 240,
      name: 'Araceli sofa',
      productType: 'sofa',
      description: '',
    ),
    ProductModel(
      id: 3,
      imagePath: 'assets/sofa3.png',
      price: 760,
      name: 'Primose sofa',
      productType: 'sofa',
      description: '',
    ),
    ProductModel(
      id: 4,
      imagePath: 'assets/sofa4.png',
      price: 332,
      name: 'Nolin sofa',
      productType: 'sofa',
      description: '',
    ),
    ProductModel(
      id: 5,
      imagePath: 'assets/sofa5.png',
      price: 500,
      name: 'Crandall sofa',
      productType: 'sofa',
      description: '',
    ),
    ProductModel(
      id: 6,
      imagePath: 'assets/sofa-2.png',
      price: 550,
      name: 'Donham sofa',
      productType: 'sofa',
      description: '',
    ),
  ];
  static List<ProductModel> bed = [
    ProductModel(
      id: 1,
      imagePath: 'assets/bed1.png',
      price: 240,
      name: 'Matteo bed',
      productType: 'bed',
      description: '',
    ),
    ProductModel(
      id: 2,
      imagePath: 'assets/bed2.png',
      price: 240,
      name: 'Araceli bed',
      productType: 'bed',
      description: '',
    ),
    ProductModel(
      id: 3,
      imagePath: 'assets/bed3.png',
      price: 760,
      name: 'Primose bed',
      productType: 'bed',
      description: '',
    ),
    ProductModel(
      id: 4,
      imagePath: 'assets/bed4.png',
      price: 332,
      name: 'Nolin bed',
      productType: 'bed',
      description: '',
    ),
    ProductModel(
      id: 5,
      imagePath: 'assets/bed5.png',
      price: 500,
      name: 'Crandall bed',
      productType: 'bed',
      description: '',
    ),
    ProductModel(
      id: 6,
      imagePath: 'assets/bed6.png',
      price: 550,
      name: 'Donham bed',
      productType: 'bed',
      description: '',
    ),
  ];
  static List<ProductModel> tables = [
    ProductModel(
      id: 1,
      imagePath: 'assets/table1.png',
      price: 240,
      name: 'Matteo table',
      productType: 'table',
      description: '',
    ),
    ProductModel(
      id: 2,
      imagePath: 'assets/table2.png',
      price: 240,
      name: 'Araceli table',
      productType: 'table',
      description: '',
    ),
    ProductModel(
      id: 3,
      imagePath: 'assets/table3.png',
      price: 760,
      name: 'Primose table',
      productType: 'table',
      description: '',
    ),
    ProductModel(
      id: 4,
      imagePath: 'assets/table4.png',
      price: 332,
      name: 'Nolin table',
      productType: 'table',
      description: '',
    ),
    ProductModel(
      id: 5,
      imagePath: 'assets/table5.png',
      price: 500,
      name: 'Crandall table',
      productType: 'table',
      description: '',
    ),
    ProductModel(
      id: 6,
      imagePath: 'assets/table6.png',
      price: 550,
      name: 'Donham table',
      productType: 'table',
      description: '',
    ),
  ];

  static List<ProductModel> bestOffers = [
    ProductModel(
      id: 7,
      imagePath: 'assets/sofa-1.png',
      price: 240,
      name: 'Ingrit MV',
      productType: 'Sofa',
      description: '',
    ),
    ProductModel(
      id: 8,
      imagePath: 'assets/sofa-2.png',
      price: 240,
      name: 'Montesque',
      productType: 'Sofa',
      description: '',
    ),
    ProductModel(
      id: 9,
      imagePath: 'assets/sofa-3.png',
      price: 760,
      name: 'Nolin Sofa',
      productType: 'Sofa',
      description: '',
    ),
    ProductModel(
      id: 10,
      imagePath: 'assets/sofa-1.png',
      price: 240,
      name: 'Ingrit MV',
      productType: 'Sofa',
      description: '',
    ),
    ProductModel(
      id: 11,
      imagePath: 'assets/sofa-2.png',
      price: 240,
      name: 'Montesque',
      productType: 'Sofa',
      description: '',
    ),
    ProductModel(
      id: 12,
      imagePath: 'assets/sofa-3.png',
      price: 760,
      name: 'Nolin Sofa',
      productType: 'Sofa',
      description: '',
    ),
    ProductModel(
      id: 13,
      imagePath: 'assets/bed1.png',
      price: 260,
      name: 'Nolin bed',
      productType: 'bed',
      description: '',
    ),
    ProductModel(
      id: 14,
      imagePath: 'assets/bed3.png',
      price: 760,
      name: 'Nolin bed',
      productType: 'bed',
      description: '',
    ),
    ProductModel(
      id: 15,
      imagePath: 'assets/bed3.png',
      price: 760,
      name: 'Nolin bed',
      productType: 'bed',
      description: '',
    ),
    ProductModel(
      id: 16,
      imagePath: 'assets/table1.png',
      price: 760,
      name: 'Nolin table',
      productType: 'table',
      description: '',
    ),
    ProductModel(
      id: 17,
      imagePath: 'assets/table3.png',
      price: 760,
      name: 'Nolin table',
      productType: 'table',
      description: '',
    ),
    ProductModel(
      id: 18,
      imagePath: 'assets/table4.png',
      price: 760,
      name: 'Nolin table',
      productType: 'table',
      description: '',
    ),
    ProductModel(
      id: 19,
      imagePath: 'assets/3.png',
      price: 760,
      name: 'Nolin Armchairs',
      productType: 'chair',
      description: '',
    ),
    ProductModel(
      id: 20,
      imagePath: 'assets/2.png',
      price: 760,
      name: 'Nolin Armchairs',
      productType: 'chair',
      description: '',
    ),
  ];
}
